### ISSUE TITLE
Should return `info_hash` after successfully uploading a torrent

### ISSUE THREAD

**Issue by WarmBeer** [torrust/torrust-index-backend#146]
Currently, the backend returns only the `torrent_id` of the newly uploaded torrent. Because of our change to using the `info_hash` as the main identifier for a torrent, we also need to have that `info_hash` return to the frontend after uploading.

**Comment by josecelano** [comment]
Hey @WarmBeer, I would even consider getting rid of the torrent id totally. I mean I would remove the `torrent_id` from all tables. That would make it harder to keep entity constraints but I think in general it has more pros than cons.

This might be a controversial topic: UUID vs databases autoincrement ID.

For me, one of the main advantages is you decouple your data from the database, which means we could export/import data easily. And we have a natural ID which is the infohash.

If we do it we have to be sure we do not have any case where inhohash can be duplicated for an entity. For such cases, we can add a UUID.

[After changing the API to use infohashes ](https://github.com/torrust/torrust-index-backend/pull/140)I think we are going to have more cases like this.

**Comment by josecelano** [comment]
By the way, this change will improve this [test](https://github.com/torrust/torrust-index-backend/blob/develop/tests/e2e/contexts/torrent/contract.rs#L319-L323).

**Comment by josecelano** [comment]
> Hey @WarmBeer, I would even consider getting rid of the torrent id totally. I mean I would remove the `torrent_id` from all tables. That would make it harder to keep entity constraints but I think in general it has more pros than cons.
> 
> This might be a controversial topic: UUID vs databases autoincrement ID.
> 
> For me, one of the main advantages is you decouple your data from the database, which means we could export/import data easily. And we have a natural ID which is the infohash.
> 
> If we do it we have to be sure we do not have any case where inhohash can be duplicated for an entity. For such cases, we can add a UUID.
> 
> [After changing the API to use infohashes ](https://github.com/torrust/torrust-index-backend/pull/140)I think we are going to have more cases like this.

We were discussing this. See: https://github.com/torrust/torrust-index-backend/discussions/149
