### ISSUE TITLE
Publish `2.0.0-alpha.1` crate

### ISSUE THREAD

**Issue by josecelano** [torrust/torrust-index-backend#152]
Testing the:

- Docker image release workflow
- Package release on crates.io

I'm following the version convention used on [torrust-tracker](https://github.com/torrust/torrust-tracker/releases).

**Comment by josecelano** [comment]
Hi @WarmBeer to publish docker images you have to set up the environment like the tracker. I can't do it:

![image](https://github.com/torrust/torrust-index-backend/assets/58816/cb63a979-ff18-408e-8e8d-a172892bc5e8)

**Comment by josecelano** [comment]
The [package](https://crates.io/crates/torrust-index-backend) was published on [crates.io](https://crates.io/crates/torrust-index-backend).

**Comment by WarmBeer** [comment]
Hi @josecelano ,

I have added the following environment to torrust/torrust-index-backend:

![Screenshot 2023-05-17 at 09 05 45](https://github.com/torrust/torrust-index-backend/assets/12992260/15b5a365-e706-4e28-8eaf-693a560a68ea)

**Comment by josecelano** [comment]
@WarmBeer it seems the credentials are wrong: https://github.com/torrust/torrust-index-backend/actions/runs/5002547167/jobs/8962758264#step:4:23

**Comment by josecelano** [comment]
> Hi @josecelano ,
> 
> I thought I had to add the `torrust/` prefix to the repository name as that is how it shows in the Docker Hub UI: `torrust/index-backend`. I have now however removed the prefix and just set `index-backend`. I also changed the username and repository variables to be normal env vars instead of secrets like you suggested. Third time is the charm? :)

Hey @WarmBeer sorry :-(, you cannot change the var from secret to normal var without changing the workflow, because they are used like this:

```
DOCKER_HUB_USERNAME: "${{ secrets.DOCKER_HUB_USERNAME }}"
```

Sorry, I did not mention it. We can open a new issue for that.

**Comment by WarmBeer** [comment]
@josecelano Oh no haha, should I make them all secrets again or did you update the workflow?

**Comment by josecelano** [comment]
> @josecelano Oh no haha, should I make them all secrets again or did you update the workflow?

Change them don't he settings for the time being, and I will create a new issue to change the workflow.

**Comment by josecelano** [comment]
I've fixed the env secrets and published the docker image ([3.0.0-alpha.2](https://hub.docker.com/layers/torrust/index-backend/3.0.0-alpha.2/images/sha256-a19e6e5dccfb6772adac81714d4d6b91fc09344bb13d435b19d1875898e6b4d5?context=explore)) manually.
