### ISSUE TITLE
Tests: Tags field missing in TorrentDetails (test) struct

### ISSUE THREAD

**Issue by mario-nt** [torrust/torrust-index-backend#273]
The TorrentDetails struct is missing the tags field:

```rust
#[derive(Deserialize, PartialEq, Debug)]
pub struct TorrentDetails {
    pub torrent_id: Id,
    pub uploader: String,
    pub info_hash: String,
    pub title: String,
    pub description: String,
    pub category: Category,
    pub upload_date: UtcDateTime,
    pub file_size: u64,
    pub seeders: u64,
    pub leechers: u64,
    pub files: Vec<File>,
    pub trackers: Vec<String>,
    pub magnet_link: String,
}
```

https://github.com/torrust/torrust-index-backend/blob/develop/tests/common/contexts/torrent/responses.rs#L49

**Comment by da2ce7** [comment]
@mario-nt  thankyou for noticing this. In please use a github codeblock instead of a screenshot, and include a link to the source code.

**Comment by mario-nt** [comment]
@da2ce7 I have updated the comment. It was actually @josecelano who told me that the tags field was missing.

**Comment by josecelano** [comment]
Yes, [I realized when I was reviewing the PR](https://github.com/torrust/torrust-index-backend/pull/265#pullrequestreview-1609813021).
