### ISSUE TITLE
Initial user/admin creation

### ISSUE THREAD

**Issue by danmons** [torrust/torrust-index-backend#28]
I've successfully installed the three components of Torrust (tracker, index-backend, index-frontend) and have it all appearing in a client side browser, but can't log in.

My index-backend `data.db` has a table `torrust_users` which is empty, and I can populate it with data via the command line `sqlite3` tool, but don't know how to hash a password correctly to be recognised as valid and let me log in. 

Is there a command line tool to do this for me? Alternatively is there a simple `openssl` style command to generate the hashed password?

**Comment by WarmBeer** [comment]
Hey @danmons ,

You just need to register for an account using the torrust-index-frontend. The first account you create will be the administrator account.

Hope this helps

**Comment by danmons** [comment]
Thanks.  I couldn't get the sign up working at first, as email wasn't working.  I've got a local internal postfix relay configured with no authentication  (itself out to an external authenticated relay), and torrust-index-backend kept throwing the following error:

```
Failed to send email: internal client error: No compatible authentication mechanism was found
```

It seems to EHLO, but then gives up.  From `mail.log`:

```
Jun 14 16:14:12 torrust postfix/smtpd[51129]: connect from localhost[127.0.0.1]
Jun 14 16:14:12 torrust postfix/smtpd[51129]: lost connection after EHLO from localhost[127.0.0.1]
Jun 14 16:14:12 torrust postfix/smtpd[51129]: disconnect from localhost[127.0.0.1] ehlo=1 commands=1
```

Is there a way to tell `torrust-index-backend` to not attempt authentication?  Currently config.toml says:

```
username = ""
password = ""
```

At any rate, I set `email_verification_enabled` to `false` and that at least got my administrator account working.

**Comment by WarmBeer** [comment]
I suppose this issue was closed by setting `email_verification_enabled` to `false`.
