### ISSUE TITLE
[bug] users not getting logged out when their sessions expire

### ISSUE THREAD

**Issue by ldpr** [torrust/torrust-index-backend#47]
[moved from here torrust/torrust-index/issues/82]

this is a pretty painful bug, i actually thought there was an issue open already.

in short:

    user logs in
    user doesn't log out and keeps the same session active for X amount of weeks
    eventually the session will time out (but they will still show as logged in) and any torrents they download won't work - they show as "400 error unauthenticated" - AKA no passkey.

Having users do this:

    Delete the torrent from the client
    Sign out from the site
    Sign back in again and download the torrent fresh
    re-add new torrent - this fixes it.

This would be a huge QOL improvement for us - again, thanks so much guys, you're the best

**Comment by da2ce7** [comment]
@ldpr Thank-you for your descriptive bug report. We are currently working on a large refactor of the backed, we will circle around and focus on this issue once this refactor has been done. Sorry for the delay.
