### ISSUE TITLE
Add minimum length for torrent titles

### ISSUE THREAD

**Issue by WarmBeer** [torrust/torrust-index-backend#72]

**Comment by alexohneander** [comment]
How do you imagine the minimum.
Should the add_torrent check if the title has min X characters and otherwise throw a BadRequest?

@josecelano

**Comment by da2ce7** [comment]
Welcome @alexohneander ,

You can add a title-too-short error to the ServiceError Enum in https://github.com/torrust/torrust-index-backend/blob/develop/src/errors.rs

**Comment by alexohneander** [comment]
@da2ce7 I had seen that too and wasn't sure if that was desired.
I extend of course :)

**Comment by josecelano** [comment]
Closed via https://github.com/torrust/torrust-index-backend/pull/239
